<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.BinarySerialization\CK.BinarySerialization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.Poco.Exc.Json" Version="33.0.0--ci.13" />
    <PackageReference Include="CK.StObj.Model" Version="33.0.0--ci.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.BinarySerialization\CK.BinarySerialization.csproj" />
  </ItemGroup>
</Project>